name: Build Documentation
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install VTK
        run: |
          pip uninstall vtk -y
          pip install --extra-index-url https://wheels.vtk.org vtk-osmesa
      - name: List
        run: pip list
      - name: Build Documentation
        working-directory: doc
        run: make html
      - name: Stash build
        uses: actions/upload-artifact@v3
        with:
          name: doc-build
          path: doc/_build

  deploy:
    name: Publish Documentation
    runs-on: ubuntu-latest
    needs: build-doc
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: doc-build
          path: doc/_build
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/_build/html
